#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 GFZ Helmholtz Centre for Geosciences
# SPDX-FileContributor: Sahil Jhawar
#
# SPDX-License-Identifier: Apache-2.0

"""PreToolUse hook for Edit/Write: block hand-edits inside GENERATED marker blocks.

`el_paso/typing.py`, `el_paso/dataset/metadata.py`, and `el_paso/dataset/dataset_implementations.py`
each contain code between `# BEGIN GENERATED ...` / `# END GENERATED ...` markers, and matching
docstring blocks between `<!-- BEGIN GENERATED ... DOCS -->` / `<!-- END GENERATED ... DOCS -->`
markers. Both are regenerated by `hooks/generate_metadata_stubs.py` from the data standards
(`el_paso/data_standards/gfz_standard.py`, `prbem_standard.py`) and must never be hand-edited.

Exit code 2 blocks the tool call and shows stderr to Claude. Anything this hook cannot make
sense of (missing file, unreadable payload, no markers found) is let through rather than
blocked, since a false block is worse than deferring to the rule stated in CLAUDE.md.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

GENERATED_FILES = (
    "el_paso/typing.py",
    "el_paso/dataset/metadata.py",
    "el_paso/dataset/dataset_implementations.py",
)

# Matches both the `# BEGIN/END GENERATED <NAME>` code markers and the
# `<!-- BEGIN/END GENERATED <NAME> DOCS -->` docstring markers. Blocks never nest in these
# files, so pairing each BEGIN with the next END (regardless of name) is enough.
BEGIN_RE = re.compile(r"[ \t]*(?:#\s*BEGIN GENERATED\b.*|<!--\s*BEGIN GENERATED\b.*?-->)")
END_RE = re.compile(r"[ \t]*(?:#\s*END GENERATED\b.*|<!--\s*END GENERATED\b.*?-->)")


def _matches_generated_file(path_str: str) -> str | None:
    """Return the matching entry in GENERATED_FILES if `path_str` names one, else None."""
    posix_path = Path(path_str).as_posix()
    for rel in GENERATED_FILES:
        if posix_path == rel or posix_path.endswith("/" + rel):
            return rel
    return None


def _generated_blocks(text: str) -> list[str]:
    """Return the text of every GENERATED block (markers included), in order."""
    blocks = []
    pos = 0
    while True:
        begin = BEGIN_RE.search(text, pos)
        if not begin:
            break
        end = END_RE.search(text, begin.end())
        if not end:
            break
        blocks.append(text[begin.start() : end.end()])
        pos = end.end()
    return blocks


def _apply_edit(old_content: str, tool_input: dict) -> str | None:
    old_string = tool_input.get("old_string", "")
    new_string = tool_input.get("new_string", "")
    if old_string == "" or old_string not in old_content:
        return None  # nothing to simulate; the Edit tool itself will reject this
    count = -1 if tool_input.get("replace_all") else 1
    return old_content.replace(old_string, new_string, count)


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except ValueError:
        return 0

    tool_name = payload.get("tool_name", "")
    if tool_name not in {"Edit", "Write"}:
        return 0

    tool_input = payload.get("tool_input", {})
    rel = _matches_generated_file(tool_input.get("file_path", ""))
    if not rel:
        return 0

    try:
        old_content = Path(tool_input["file_path"]).read_text()
    except (OSError, KeyError):
        return 0  # file doesn't exist yet; nothing generated to protect

    if tool_name == "Write":
        new_content = tool_input.get("content", "")
    else:
        new_content = _apply_edit(old_content, tool_input)
        if new_content is None:
            return 0

    if _generated_blocks(old_content) != _generated_blocks(new_content):
        sys.stderr.write(
            f"Blocked: this change touches a `# BEGIN/END GENERATED` or "
            f"`<!-- BEGIN/END GENERATED ... DOCS -->` block in {rel}. These blocks are "
            "regenerated by hooks/generate_metadata_stubs.py from the data standards "
            "(el_paso/data_standards/gfz_standard.py, prbem_standard.py); never hand-edit them. "
            "Change the relevant standard's `variable_infos` instead and run "
            "`.venv/bin/python hooks/generate_metadata_stubs.py` to regenerate.\n"
        )
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
