# SPDX-FileCopyrightText: 2025 GFZ Helmholtz Centre for Geosciences
# SPDX-FileContributor: Bernhard Haas
#
# SPDX-License-Identifier: Apache-2.0

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml

  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff-check
        types_or: [python, pyi]
        files: ^el_paso/
      - id: ruff-format
        types_or: [python, pyi]
        files: ^el_paso/

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: v0.0.77
    hooks:
      - id: ty
        files: ^el_paso/

  - repo: local
    hooks:
      - id: generate-metadata-stubs
        name: generate-metadata-stubs
        entry: python hooks/generate_metadata_stubs.py
        language: system
        pass_filenames: false
        files: ^(el_paso/data_standards/(gfz_standard|prbem_standard)\.py|scripts/generate_metadata_stubs\.py)$
