# SPDX-FileCopyrightText: 2025 GFZ Helmholtz Centre for Geosciences
# SPDX-FileContributor: Bernhard Haas
# SPDX-FileContributor: Sahil Jhawar
#
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "el_paso"
version = "2.1.3rc0"
description = "EL-PASO is a Python framework designed to streamline the download, processing, and saving of satellite particle observation data."
authors = [{ name = "Bernhard Haas", email = "bhaas@gfz.de" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astropy>=7.2.0",
    "cdflib==1.3.8",
    "gitpython==3.1.46",
    "joblib>=1.4.0",
    "matplotlib>=3.10.8",
    "netcdf4>=1.7.2",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "pytest>=9.0.2",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.5",
    "rich>=13.0.0",
    "richpool>=0.1.2",
    "scipy>=1.17",
    "sscws==2.4.6",
    "swvo>=1.2.7rc0",
    "tabulate==0.9.0",
    "tqdm>=4.67.2",
    "typer>=0.15",
    "wget>=3.2",
    "wheel==0.46.3",
    "skyfield==1.54",
    "dotenv>=0.9.9",
    "coverage>=7.14.0",
    "xarray>=2026.4.0",
    "ty>=0.0.37",
    "ruff>=0.15.13",
    "pre-commit",
]
license = "(Apache-2.0 OR LGPL-3.0-only)"
license-files = ["LICENSES/*"]

classifiers = [
    "Programming Language :: Python :: 3",
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Operating System :: POSIX',
    'Operating System :: Unix',
    'Operating System :: MacOS',
]


[project.scripts]
el-paso = "el_paso.cli.app:main"

[tool.hatch.build.targets.wheel]
packages = ["el_paso"]

[tool.hatch.build.hooks.custom]

[project.urls]
Homepage = "https://github.com/GFZ/EL_PASO"
Tracker = "https://github.com/GFZ/EL_PASO/issues"
Documentation = "https://el-paso.readthedocs.io/en/latest/"

[tool.bumpver]
current_version = "2.1.3rc0"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = ['version = "{version}"']
"el_paso/__init__.py" = ['__version__ = "{version}"']
"el_paso.def" = ['    Version {version}']

[tool.ty.src]
exclude = [
    "el_paso/saving_strategies/density_netcdf_strategy.py",
    "el_paso/dataset/scripts/create_RBSP_line_data.py",
]
include = ["el_paso/**/*.py"]
