# SPDX-FileCopyrightText: 2026 GFZ Helmholtz Centre for Geosciences
# SPDX-FileContributor: Bernhard Haas
#
# SPDX-License-Identifier: Apache-2.0

"""The ``el-paso`` command line entry point.

Groups every recipe under :mod:`el_paso.recipes` into one command tree, one
sub-command group per mission::

    el-paso list
    el-paso poes meped --start-time 2013-03-16 --satellite noaa15
    el-paso rbsp mageis-electrons --mag-field TS04 --bin-cadence 5min

Each command is generated by :func:`el_paso.cli.recipe_cli.build_recipe_command` from
the recipe's own signature, using the ``CLI_DEFAULTS`` declared in the recipe
module. That is the same builder the recipes' own ``python -m`` entry points use,
so both ways of invoking a recipe expose exactly the same options.
"""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING, NamedTuple

import typer
from rich.console import Console
from rich.table import Table

from el_paso.cli.recipe_cli import build_recipe_command, parse_docstring

if TYPE_CHECKING:
    from collections.abc import Callable


class RecipeEntry(NamedTuple):
    """One recipe as it is exposed on the ``el-paso`` command line.

    Attributes:
        mission: The sub-command group the recipe lives in (e.g. ``"poes"``).
        command: The sub-command name within that group (e.g. ``"meped"``).
        module: Import path of the module defining the recipe.
        function: Name of the recipe function inside that module.
    """

    mission: str
    command: str
    module: str
    function: str


RECIPES: tuple[RecipeEntry, ...] = (
    RecipeEntry("arase", "mepe", "el_paso.recipes.arase.process_arase_mepe", "process_arase_mepe"),
    RecipeEntry(
        "arase", "pwe-density", "el_paso.recipes.arase.process_arase_pwe_densities", "process_arase_pwe_density"
    ),
    RecipeEntry("arase", "xep", "el_paso.recipes.arase.process_arase_xep", "process_arase_xep"),
    RecipeEntry(
        "arase", "xep-realtime", "el_paso.recipes.arase.process_arase_xep_realtime", "process_arase_xep_real_time"
    ),
    RecipeEntry("dmsp", "ssj", "el_paso.recipes.dmsp.process_dmsp_ssj_electrons", "process_dmsp_ssj_electrons"),
    RecipeEntry("esa", "ngrm", "el_paso.recipes.esa.process_ngrm_satellite", "process_ngrm_electron_fluxes"),
    RecipeEntry("goes", "mps-high", "el_paso.recipes.goes.process_goes_r_mps_high", "process_goes_r_mps_high"),
    RecipeEntry("goes", "realtime", "el_paso.recipes.goes.process_goes_realtime", "process_goes_real_time"),
    RecipeEntry("gps", "cxd", "el_paso.recipes.gps.process_gps", "process_gps_data"),
    RecipeEntry("poes", "meped", "el_paso.recipes.poes.process_poes_meped", "process_poes_meped_electron"),
    RecipeEntry("poes", "ted", "el_paso.recipes.poes.process_poes_ted", "process_poes_ted_electron"),
    RecipeEntry(
        "probav", "ept-electrons", "el_paso.recipes.probav.process_ept_electron_fluxes", "process_ept_electron_fluxes"
    ),
    RecipeEntry(
        "probav", "ept-protons", "el_paso.recipes.probav.process_ept_proton_fluxes", "process_ept_proton_fluxes"
    ),
    RecipeEntry("rbsp", "ect-combined", "el_paso.recipes.rbsp.process_rbsp_ect_combined", "process_rbsp_ect_combined"),
    RecipeEntry(
        "rbsp",
        "density-combined",
        "el_paso.recipes.rbsp.process_rbsp_efw_emfisis_density_combined",
        "process_rbsp_efw_emfisis_density_combined",
    ),
    RecipeEntry(
        "rbsp", "emfisis-waves", "el_paso.recipes.rbsp.process_rbsp_emfisis_waves", "process_rbsp_emfisis_waves"
    ),
    RecipeEntry(
        "rbsp", "hope-electrons", "el_paso.recipes.rbsp.process_rbsp_hope_electrons", "process_rbsp_hope_electrons"
    ),
    RecipeEntry("rbsp", "hope-protons", "el_paso.recipes.rbsp.process_rbsp_hope_protons", "process_rbsp_hope_protons"),
    RecipeEntry(
        "rbsp",
        "mageis-electrons",
        "el_paso.recipes.rbsp.process_rbsp_mageis_electrons",
        "process_rbsp_mageis_electrons",
    ),
    RecipeEntry(
        "rbsp", "mageis-protons", "el_paso.recipes.rbsp.process_rbsp_mageis_protons", "process_rbsp_mageis_protons"
    ),
    RecipeEntry(
        "rbsp", "rbspice-protons", "el_paso.recipes.rbsp.process_rbsp_rbspice_protons", "process_rbsp_rbspice_protons"
    ),
)


def load_recipe(entry: RecipeEntry) -> tuple[Callable[..., None], dict[str, object]]:
    """Import a recipe and return its function together with its CLI defaults.

    Args:
        entry (RecipeEntry): The registry entry to load.

    Returns:
        tuple[Callable[..., None], dict[str, object]]: The recipe function and the
        ``CLI_DEFAULTS`` declared in its module (an empty dict if it declares none).
    """
    module = importlib.import_module(entry.module)
    return getattr(module, entry.function), getattr(module, "CLI_DEFAULTS", {})


def _summary(entry: RecipeEntry) -> str:
    """Return the one-line summary of a recipe, importing it lazily."""
    try:
        func, _ = load_recipe(entry)
    except Exception as exc:  # noqa: BLE001
        return f"[red]failed to import: {exc}[/red]"
    summary, _ = parse_docstring(func.__doc__)
    return summary


app = typer.Typer(
    name="el-paso",
    help="Download, process and save satellite particle observation data.",
    no_args_is_help=True,
    pretty_exceptions_show_locals=False,
)

_mission_apps: dict[str, typer.Typer] = {}

for _entry in RECIPES:
    if _entry.mission not in _mission_apps:
        mission_app = typer.Typer(name=_entry.mission, help=f"{_entry.mission.upper()} recipes.", no_args_is_help=True)
        _mission_apps[_entry.mission] = mission_app
        app.add_typer(mission_app)

    _func, _defaults = load_recipe(_entry)
    _mission_apps[_entry.mission].command(name=_entry.command)(build_recipe_command(_func, defaults=_defaults))


@app.command("list")
def list_recipes() -> None:
    """List every available recipe."""
    table = Table(title="EL-PASO recipes")
    table.add_column("Command", style="bold cyan", no_wrap=True)
    table.add_column("Module", style="dim", no_wrap=True)
    table.add_column("Description")

    for entry in RECIPES:
        table.add_row(f"el-paso {entry.mission} {entry.command}", entry.module, _summary(entry))

    Console().print(table)


def main() -> None:
    """Run the ``el-paso`` command line application."""
    app()


if __name__ == "__main__":
    main()
